#!/bin/bash
 
#PBS -N job_script
#PBS -l select=1:ncpus=1:mem=1gb
#PBS -l walltime=00:10:00
#PBS -j oe
#PBS -k oed
#PBS -M me@unsw.edu.au
#PBS -m ae


# Set the total number of jobs that you want to run.
MAX_INDEX_VALUE=10000
 

# Set the point at which you 
export UPPER_END=$(($PBS_ARRAY_INDEX + 100))


# If your job number plus 100 is divisable by 500 then
# submit the next batch of 500 jobs.
 
if (($UPPER_END % 500 == 0))
then
    export NEXT_MAX=$(($UPPER_END + 500))
    export UPPER_END=$UPPER_END;         
    # Only submit a new batch if the upper limit will be less than the max.
    if [ "$UPPER_END" -lt "$MAX_INDEX_VALUE" ];
        then
        # The actual job submission line
        qsub -J ${UPPER_END}-${NEXT_MAX} $0
    fi
fi


# Now we run the commands that include our actual calculations. The
# environment variable $PBS_ARRAY_INDEX is available for use.

module add matlab/2018b
date


##########
# Save this file as myjob.pbs and submit it as
# "qsub -J 1-500 myjob.pbs" to get started.
##########